name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew :app:assembleZegoDebug :app:assembleAgoraDebug :app:testZegoDebugUnitTest :app:testAgoraDebugUnitTest :app:lintZegoDebug :app:lintAgoraDebug

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: |
            app/build/outputs/apk/zego/debug/
            app/build/outputs/apk/agora/debug/
